<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir).'/build';

return array(
    'Symfony\\Polyfill\\Ctype\\' => array($vendorDir . '/symfony/polyfill-ctype'),
    'Symfony\\Component\\Yaml\\' => array($vendorDir . '/symfony/yaml'),
    'Sober\\Models\\Model\\' => array($vendorDir . '/soberwp/models/src/Model'),
    'Sober\\Models\\' => array($vendorDir . '/soberwp/models/src'),
    'Saltus\\WP\\Plugin\\Saltus\\PluginFrameworkDemo\\Tests\\' => array($baseDir . '/../tests'),
    'Saltus\\WP\\Plugin\\Saltus\\PluginFrameworkDemo\\' => array($baseDir . '/../src'),
    'Saltus\\WP\\Framework\\' => array($vendorDir . '/saltus/framework/src'),
    'Noodlehaus\\' => array($vendorDir . '/hassankhan/config/src'),
    'Composer\\Installers\\' => array($vendorDir . '/composer/installers/src/Composer/Installers'),
);
