<?php
/**
 * Works around Strauss's broken alias autoloader for global-namespace Codestar classes.
 *
 * @package Saltus\WP\Plugin\Saltus\PluginFrameworkDemo
 */

namespace Saltus\WP\Plugin\Saltus\PluginFrameworkDemo\Plugin;

/**
 * Eagerly loads the Codestar function files that Strauss's aliasing leaves dangling.
 *
 * ## The bug
 *
 * Codestar builds its field classes by string name — `'CSF_Field_' . $field['type']` in
 * `setup.class.php:619` — so it asks for the *un-prefixed* `CSF_Field_typography`. Strauss cannot
 * rewrite a runtime-constructed name, so it generates `vendor/composer/autoload_aliases.php`: an
 * autoloader that fabricates `CSF_Field_typography extends Saltus_..._CSF_Field_typography {}`
 * shims on demand, plus eagerly-defined shims for global *functions* at the top of that file.
 *
 * The class half is broken. Strauss records `'namespace' => '\\'` for global-namespace classes, and
 * its template does `isset($class['namespace'])` — true for `'\\'` — emitting `namespace \;`, a
 * parse error. So the class shim never materialises.
 *
 * The function half, however, *is* defined: `csf_get_google_fonts()` exists and forwards to
 * `saltus_..._csf_get_google_fonts()`. But that prefixed target lives in
 * `fields/typography/google-fonts.php`, which Codestar includes lazily from inside the real
 * prefixed class's `enqueue()`. Since the class shim failed, the include never runs, and the
 * forwarding shim points at nothing:
 *
 *     csf_get_google_fonts() defined ......... true
 *     saltus_..._csf_get_google_fonts() ..... false   <-- fatal on call
 *
 * Any code path reaching a `typography` field fatals with
 * `Call to undefined function saltus_..._csf_get_google_fonts()`.
 *
 * ## Why fix it here
 *
 * `vendor/` and `vendor-prefixed/` are regenerated by `composer prefix-namespaces`, so patching
 * either would be silently undone. The real fix is upstream in Strauss (treat `'\\'` as the global
 * namespace and emit no `namespace` statement) — tracked as ROADMAP Phase 4 task 1. Until then this
 * closes the gap from plugin code by loading the deferred function files up front, so the shims
 * always have a target.
 *
 * `icon` is affected by the same aliasing but survives page loads: its `enqueue()` only registers
 * footer actions, and the AJAX handler that needs `csf_get_default_icons()` includes the icon file
 * immediately before calling it. Loaded here anyway for completeness.
 */
class CodestarCompat {

	/**
	 * Codestar function files that define prefixed `csf_*` helpers but are only included lazily.
	 *
	 * Relative to the prefixed Codestar root.
	 *
	 * @var list<string>
	 */
	private const DEFERRED_FUNCTION_FILES = array(
		'fields/typography/google-fonts.php',
		'fields/icon/fa5-icons.php',
	);

	/**
	 * Register the compatibility shim.
	 *
	 * Runs on `init` at a late priority: Codestar's own bootstrap has to have run first, and the
	 * files guard themselves with `defined( 'ABSPATH' )`.
	 */
	public function register(): void {
		add_action( 'init', array( $this, 'load_deferred_function_files' ), 20 );
	}

	/**
	 * Include the deferred Codestar function files if their prefixed functions are missing.
	 */
	public function load_deferred_function_files(): void {
		// Every Codestar file opens with `if ( ! defined( 'ABSPATH' ) ) { die; }`, which would
		// terminate the process outright outside WordPress — including under PHPUnit.
		if ( ! defined( 'ABSPATH' ) ) {
			return;
		}

		$root = $this->codestar_root();
		if ( $root === '' ) {
			return;
		}

		foreach ( self::DEFERRED_FUNCTION_FILES as $relative_path ) {
			$path = $root . '/' . $relative_path;

			if ( ! is_file( $path ) || ! is_readable( $path ) ) {
				continue;
			}

			require_once $path;
		}
	}

	/**
	 * Locate the prefixed Codestar library root.
	 *
	 * Resolved from a known prefixed class rather than a hardcoded path, so a rebranded plugin
	 * with a different Strauss prefix still finds it.
	 *
	 * @return string Absolute path without a trailing slash, or an empty string when not found.
	 */
	private function codestar_root(): string {
		$setup_class = '\Saltus_WP_Plugin_Saltus_PluginFrameworkDemo_CSF_Setup';

		if ( ! class_exists( $setup_class ) ) {
			return '';
		}

		try {
			$reflection = new \ReflectionClass( $setup_class );
		} catch ( \ReflectionException $e ) {
			return '';
		}

		$file_name = $reflection->getFileName();
		if ( ! is_string( $file_name ) || $file_name === '' ) {
			return '';
		}

		// .../lib/codestar-framework/classes/setup.class.php -> .../lib/codestar-framework
		return dirname( $file_name, 2 );
	}
}
